Repository esmf-org/esmf, pull requests merged in 2025-05, with the labels that each got.

#396 32-bit ABI fixes
  scripts/jinja2_templating/generate_templates.py
  src/Infrastructure/Base/interface/ESMF_InfoCDefGeneric.F90
  src/Infrastructure/Base/src/ESMCI_Info.C
  src/Infrastructure/Base/src/ESMC_InfoCDefGeneric.C
  src/Infrastructure/Base/tests/ESMCI_InfoUTest.C
  src/Infrastructure/Util/include/ESMCI_Util.h
  src/Infrastructure/Util/include/ESMC_Util.h
  src/Infrastructure/Util/src/ESMCI_Util.C
  src/Infrastructure/Util/src/ESMF_FortranWordsize.cppF90
  src/Infrastructure/Util/src/ESMF_UtilTypes.F90
Labels: bug, porting

#398 Component based redirection of stdout and stderr streams
  src/Infrastructure/VM/include/ESMCI_VMKernel.h
  src/Infrastructure/VM/interface/ESMCI_VM_F.C
  src/Infrastructure/VM/interface/ESMF_VM.F90
  src/Infrastructure/VM/src/ESMCI_VMKernel.C
  src/Infrastructure/VM/tests/ESMF_VMComponentUTest.F90
  src/Superstructure/Component/src/ESMF_Comp.F90
  src/Superstructure/Component/src/ESMF_CplComp.F90
  src/Superstructure/Component/src/ESMF_GridComp.F90
  src/addon/ESMX/Comps/ESMX_Data/ESMX_Data.F90
  src/addon/ESMX/Driver/ESMX_Driver.F90
  src/addon/ESMX/README.md
  src/addon/NUOPC/doc/NUOPC_StdRedirect.tex
  src/addon/NUOPC/doc/NUOPC_refdoc.ctex
  src/addon/NUOPC/doc/makefile
  src/addon/NUOPC/src/NUOPC.F90
  src/addon/NUOPC/src/NUOPC_Base.F90
  src/addon/NUOPC/src/NUOPC_Comp.F90
  src/addon/NUOPC/src/NUOPC_Driver.F90
  src/addon/NUOPC/src/NUOPC_ModelBase.F90
Labels: feature/enhancement, NUOPC, ESMX, who: NRL

#390 Add workflow for testing MAPL
  .github/workflows/mapl-tests.yml
Labels: feature/enhancement, who: NASA

#412 Determine LLVM Flang runtime libs dynamically for backward compatibility
  build_config/Linux.llvm.default/build_rules.mk
  scripts/libs.llvm
Labels: bug, porting

#413 Address issues flagged by AddressSanitizer - low hanging fruit
  src/Infrastructure/IO/interface/ESMCI_IO_YAML_F.C
  src/Infrastructure/IO/interface/ESMF_IO_YAML.F90
  src/Infrastructure/TimeMgr/interface/ESMCI_Alarm_F.C
  src/Infrastructure/TimeMgr/interface/ESMCI_Calendar_F.C
  src/Infrastructure/TimeMgr/interface/ESMCI_Clock_F.C
  src/Infrastructure/TimeMgr/interface/ESMCI_TimeInterval_F.C
  src/Infrastructure/TimeMgr/interface/ESMCI_Time_F.C
  src/Infrastructure/VM/src/ESMCI_VM.C
  src/Infrastructure/VM/src/ESMCI_VMKernel.C
Labels: bug

#361 Add Runtime Options for logMsgAbort and abort
  src/Infrastructure/Util/src/ESMF_LogErr.F90
  src/Infrastructure/VM/interface/ESMCI_VM_F.C
  src/Infrastructure/VM/interface/ESMF_VM.F90
  src/Infrastructure/VM/src/ESMCI_VM.C
  src/Infrastructure/VM/src/ESMCI_VMKernel.C
  src/Superstructure/ESMFMod/src/ESMF_Init.F90
  src/addon/ESMX/ESMX_App.F90
  src/addon/ESMX/README.md
  src/doc/ESMF_debug.tex
Labels: feature/enhancement

#418 Fix Fujitsu build failure
  build/common.mk
  build_config/Linux.fujitsu.default/build_rules.mk
Labels: porting

#421 Build ESMF and ESMPy docs from ESMF forks
  .github/workflows/build-esmf-docs.yml
  .github/workflows/build-esmpy-docs.yml
Labels: who: NASA
