Repository esmf-org/esmf, pull requests merged in 2025-04, with the labels that each got.

#369 Make the ESMX CMake API directly usable for (complex) projects that leverage CMake
  cmake/FindESMF.cmake
  src/addon/ESMX/CMakeLists.txt
  src/addon/ESMX/Comps/ESMX_Data/CMakeLists.txt
  src/addon/ESMX/Comps/ESMX_Data/cmake/FindESMF.cmake
  src/addon/ESMX/Driver/CMakeLists.txt
  src/addon/ESMX/Driver/esmx_comp_config.py
  src/addon/ESMX/README.md
  src/addon/ESMX/cmake/FindESMF.cmake
Labels: ESMX

#375 Cleanup README badges
  .github/workflows/build-esmf-docs.yml
  .github/workflows/build-esmpy-docs.yml
  .github/workflows/esmf-all-tests.yml
  .github/workflows/test-build-spack.yml
  README.md
Labels: documentation

#377 Tone down the restrictions for the clock object in *CompCreate() API doc
  src/Superstructure/Component/src/ESMF_CplComp.F90
  src/Superstructure/Component/src/ESMF_GridComp.F90
Labels: who: NASA
